### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data-mscoco/images/val2017/000000532481.jpg'

### ISSUE THREAD

**Issue by khoa127** [DuncanZauss/Keypoint_Communities#12]
I encountered this problem while i was trying to run the evaluation  
![image](https://user-images.githubusercontent.com/57555776/142620399-dfc2b0c4-837e-481b-a0b4-871cb54c963a.png)

**Comment by DuncanZauss** [comment]
Hi @khoa127,
You have to unzip the MS COCO data and also you would need to download the corresponding WholeBody annotations as explained [here](https://openpifpaf.github.io/plugins_wholebody.html#train). If you do not have the images and the annotation files in the default location you can also specify the location via CLI. You can check all CLI options for the eval module with `python -m openpifpaf.eval -h`. These are the four CLI options to specify the image folder and annotation file locations:
```sh
data module wholebody:
  --wholebody-train-annotations WHOLEBODY_TRAIN_ANNOTATIONS
                        train annotations (default: data-
                        mscoco/annotations/person_keypoints_train2017_wholebody_pifpaf_style.json)
  --wholebody-val-annotations WHOLEBODY_VAL_ANNOTATIONS
                        val annotations (default: data-
                        mscoco/annotations/coco_wholebody_val_v1.0.json)
  --wholebody-train-image-dir WHOLEBODY_TRAIN_IMAGE_DIR
                        train image dir (default: data-mscoco/images/train2017/)
  --wholebody-val-image-dir WHOLEBODY_VAL_IMAGE_DIR
                        val image dir (default: data-mscoco/images/val2017)
```
