### ISSUE TITLE
can't run the demo

### ISSUE THREAD

**Issue by yktangac** [DuncanZauss/Keypoint_Communities#13]
Hi there, I can't run the webcam and the demo with image source either. Not sure what's happening. 
```bash
Working Environment 
OS: macOS 12.1 21C52 x86_64 
Host: iMac19,1
Kernel: 21.2.0
CPU: Intel i5-8500 (6) @ 3.00GHz
GPU: Radeon Pro 570X
```
I used miniconda to install this repo. Not sure whether it needs cuda support

**Comment by DuncanZauss** [comment]
Hi @yktangac ,
Could you please post the command that you run and the error message that you get so that I can check what might cause the problem?

**Comment by yktangac** [comment]
> Hi @yktangac , Could you please post the command that you run and the error message that you get so that I can check what might cause the problem?

Thank you for your reply, I just copied the run command from READ.md .
1. demo on webcam
```
python -m openpifpaf.video --source=0 --checkpoint=shufflenetv2k16-wholebody --long-edge=321 --horizontal-flip --show
```
terminal output 
```
Traceback (most recent call last):
  File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/__init__.py", line 11, in <module>
    cpp_extension.register_ops()
  File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/cpp_extension.py", line 26, in register_ops
    torch.ops.load_library(ext_specs.origin)
  File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/_cpp.so, 0x0006): Symbol not found: __ZNK3c104Type14isSubtypeOfExtERKS0_PNSt3__113basic_ostreamIcNS3_11char_traitsIcEEEE
  Referenced from: /Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/_cpp.so
  Expected in: /Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib
```
2. demo on source 
```
python -m openpifpaf.predict docs/soccer.jpeg --checkpoint=shufflenetv2k30-wholebody --line-width=2 --show
```
terminal output
```
Traceback (most recent call last):
  File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/__init__.py", line 11, in <module>
    cpp_extension.register_ops()
  File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/cpp_extension.py", line 26, in register_ops
    torch.ops.load_library(ext_specs.origin)
  File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/_cpp.so, 0x0006): Symbol not found: __ZNK3c104Type14isSubtypeOfExtERKS0_PNSt3__113basic_ostreamIcNS3_11char_traitsIcEEEE
  Referenced from: /Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/_cpp.so
  Expected in: /Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib
```
From the above error, does this require pytorch for its dependency? I didn't install pytorch when I create a new conda environment. Let me install it first and see whether still output this error message.

**Comment by yktangac** [comment]
I checked with pip3 list | grep torch
I do have torch and torchvision installed. seems like still having other issues
> From the above error, does this require pytorch for its dependency? I didn't install pytorch when I create a new conda environment. Let me install it first and see whether still output this error message.

**Comment by nish-sv** [comment]
I think it is because of gcc version mismatch. @DuncanZauss Can we know the gcc version that you have used

**Comment by nish-sv** [comment]
> > Hi @yktangac , Could you please post the command that you run and the error message that you get so that I can check what might cause the problem?
> 
> Thank you for your reply, I just copied the run command from READ.md .
> 
> 1. demo on webcam
> 
> ```
> python -m openpifpaf.video --source=0 --checkpoint=shufflenetv2k16-wholebody --long-edge=321 --horizontal-flip --show
> ```
> 
> terminal output
> 
> ```
> Traceback (most recent call last):
>   File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/runpy.py", line 188, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/runpy.py", line 111, in _get_module_details
>     __import__(pkg_name)
>   File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/__init__.py", line 11, in <module>
>     cpp_extension.register_ops()
>   File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/cpp_extension.py", line 26, in register_ops
>     torch.ops.load_library(ext_specs.origin)
>   File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/torch/_ops.py", line 104, in load_library
>     ctypes.CDLL(path)
>   File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/ctypes/__init__.py", line 382, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: dlopen(/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/_cpp.so, 0x0006): Symbol not found: __ZNK3c104Type14isSubtypeOfExtERKS0_PNSt3__113basic_ostreamIcNS3_11char_traitsIcEEEE
>   Referenced from: /Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/_cpp.so
>   Expected in: /Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib
> ```
> 
> 2. demo on source
> 
> ```
> python -m openpifpaf.predict docs/soccer.jpeg --checkpoint=shufflenetv2k30-wholebody --line-width=2 --show
> ```
> 
> terminal output
> 
> ```
> Traceback (most recent call last):
>   File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/runpy.py", line 188, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/runpy.py", line 111, in _get_module_details
>     __import__(pkg_name)
>   File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/__init__.py", line 11, in <module>
>     cpp_extension.register_ops()
>   File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/cpp_extension.py", line 26, in register_ops
>     torch.ops.load_library(ext_specs.origin)
>   File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/torch/_ops.py", line 104, in load_library
>     ctypes.CDLL(path)
>   File "/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/ctypes/__init__.py", line 382, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: dlopen(/Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/_cpp.so, 0x0006): Symbol not found: __ZNK3c104Type14isSubtypeOfExtERKS0_PNSt3__113basic_ostreamIcNS3_11char_traitsIcEEEE
>   Referenced from: /Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/openpifpaf/_cpp.so
>   Expected in: /Users/htang/miniconda/envs/OpenPiPaf/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib
> ```
> 
> From the above error, does this require pytorch for its dependency? I didn't install pytorch when I create a new conda environment. Let me install it first and see whether still output this error message.

It worked when I changed the versions of some packages in the requiremnts.txt file
