### ISSUE TITLE
Error while installing openpifpaf

### ISSUE THREAD

**Issue by samymdihi** [DuncanZauss/Keypoint_Communities#5]
While running the requirements.txt I got stuck on an issue regarding openpifpaf==0.13.0. It seems like the version cannot be found. Do you have a way to bypass that ?

**Comment by DuncanZauss** [comment]
I see. Could you try to install OpenPifPaf from source?
I.e. git clone OpenPifPaf and then run the following command in the folder where the setup.py file is:
```
pip install -e .
```
Also for openpifpaf 0.13.0 you need to make sure that you have a C++ compiler installed.
