### ISSUE TITLE
Questions regarding the application of this paper/code.

### ISSUE THREAD

**Issue by poornimajd** [DuncanZauss/Keypoint_Communities#7]
Hello Thank you for the open-source code and great work!
I had the following questions -

1)Can we apply this code to a use-case as follows-
A static camera is observing 2-3 moving robots in its FOV,and if I retrain the network with the images of the robot,with its corresponding ground-truth keypoints,the network can still predict the 2d keypoints of the moving robot right?

2)For this does the robot have to be at a particular distance from the camera,so that the keypoint estimation is accurate enough?Meaning is the network's accuracy dependent on "the distance the object is from the camera"?

3)Also can the network be used in a case where the camera observing the scene is moving as well as the object whose pose is to be estimated is also moving?Will the network's accuracy be effected in this case?

Any suggestions/replies are greatly appreciated!
Thank you

**Comment by DuncanZauss** [comment]
I am closing this for now. Feel free to reopen, if you have further questions.
