### ISSUE TITLE
Prediction result for soccer.jpeg is not as good as the shown image

### ISSUE THREAD

**Issue by Kairobo** [DuncanZauss/Keypoint_Communities#9]
![Screenshot from 2021-11-09 23-33-13](https://user-images.githubusercontent.com/25882352/140954912-dacabb8f-9402-49a9-917f-848e7c9de093.png)
I use the same command 'python -m openpifpaf.predict docs/soccer.jpeg --checkpoint=shufflenetv2k30-wholebody --line-width=2 --show
' to run the prediction but the hands of the front person are not aligned as your shown image.
Did you use a different weight? Or is there any other problems?

**Comment by DuncanZauss** [comment]
Hi @Kairobo,
Indeed different weights were used. I have reuploaded those weights. You can download those and then provide this local checkpoint to the predict API. For example:
```sh
wget https://github.com/DuncanZauss/openpifpaf_assets/releases/download/v0.1.0/old_sk30_wholebody.pkl
python -m openpifpaf.predict ./soccer.jpeg --checkpoint=./old_sk30_wholebody.pkl --line-width=1 --show --force-complete-pose --instance-threshold=0.1
```
